name: SAST Analysis

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  sast-frontend:
    name: Frontend SAST Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install --prefix frontend

      - name: Run ESLint
        run: npx eslint frontend/src --ext .js,.jsx

  sast-backend:
    name: Backend SAST Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'javascript'

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
